---
title: "ALA and temperature data"
author: "Fonti Kar"
date: "2024-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(galah, tidyverse, dplyr, oce, ocedata, ncdf4, sf, ggplot2, lubridate, ozmaps, raster, sp, tidync, rerddap, doParallel, patchwork, scales, arrow)

# Australia map
aus_sf <- st_transform(ozmaps::ozmap_states, crs = 4326)
```

## Get ALA data

```{r, eval=FALSE}
galah_config(email = Sys.getenv("ALA_EMAIL"),
             atlas = "Australia",
             download_reason_id = 5)


galah_call() |> 
  galah_identify("Acanthaster planci") |> 
  galah_apply_profile(ALA) |> 
  atlas_counts()

cot_general <- galah_call() |> 
  galah_identify("Acanthaster planci") |> 
  galah_apply_profile(ALA) |> 
  galah_select(group = "basic", datasetName, dataResourceName) |> 
  atlas_occurrences()

arrow::write_parquet(cot_general, paste0("data/galah/",Sys.Date(),"-cots.parquet"))
```

# Read in data

```{r}
cot_general <- read_parquet("data/galah/2024-01-20-cots.parquet")
```


Rough clean

```{r}
cot_clean <- cot_general |> 
  drop_na(decimalLatitude, decimalLongitude) |> 
  filter(duplicated(decimalLatitude) | duplicated(decimalLongitude))

cot_clean_date <- cot_clean |> 
  mutate(eventDate = as_date(eventDate), 
         eventDate = ymd(eventDate), 
         year = year(eventDate)) 

# Clean to mainland
cot_mainland <- cot_clean_date |> 
  filter(decimalLatitude < -10, decimalLatitude >= -45,
         decimalLongitude >= 113, decimalLongitude <= 155) 
```

Transform to sf and plot COT dist

```{r}
cot_sf <- cot_mainland |> 
  dplyr::select(scientificName, eventDate, year, decimalLongitude, decimalLatitude) |> 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), 
         crs = 4326)

ggplot() + 
  geom_sf(data = aus_sf) + 
  geom_sf(data = cot_sf) 
```

By year

```{r}
year_data <- cot_clean_date |> 
  filter(year > 1981) |> 
  group_by(year) |> 
  summarise(n_obs = n()) |> 
  arrange(year) |> 
  print(n = Inf) 
  

cot_obs <- ggplot(data = year_data, 
                  aes(x = year, y = n_obs)) + 
  geom_col() + 
  scale_y_continuous(breaks = breaks_extended(n = 10))

cot_obs
```


## Get temperature data

```{r}
cot_mainland |> 
  arrange(desc(eventDate)) |> 
  mutate(ymd = ymd(eventDate))
```

tidync way

```{r, eval=FALSE}
# open netcdf file and extract variables
nc = tidync(paste0("data/",data_file))

# view netcf metadata
nc 

# extract data
nc %>% 
  hyper_tibble(select_var = "sst") |> 
  filter(lat <=-10 & lat >= -25)


lat = ncvar_get(nc, "lat")
lon = ncvar_get(nc, "lon")
time = ncvar_get(nc, "time")
sst = ncvar_get(nc, "sst")

# close netcdf
nc_close(nc)


which(lat <=(-10) & lat >=(-25))

temp_QLD <- sst[,261:320]
temp_QLD_raster <- raster(temp_QLD)

temp_QLD_raster_df <- temp_QLD_raster |> raster::as.data.frame(xy = TRUE)

names(temp_QLD_raster)
head(temp_QLD_raster)

ggplot() +
  geom_raster(data = temp_QLD_raster_df, aes(x = x, y = y, fill = layer))
plot(t(temp_QLD_raster))
```

https://cran.r-project.org/web/packages/heatwaveR/vignettes/OISST_preparation.html

```{r, eval=FALSE}
# Meta-data
rerddap::info(datasetid = "ncdcOisst21Agg_LonPM180", url = "https://coastwatch.pfeg.noaa.gov/erddap/")


OISST_sub_dl <- function(time_df){
  OISST_dat <- griddap(datasetx = "ncdcOisst21Agg_LonPM180", 
                       url = "https://coastwatch.pfeg.noaa.gov/erddap/", 
                       time = c(time_df$start, time_df$end), 
                       zlev = c(0, 0),
                       latitude = c(-10, -45),
                       longitude = c(113, 155),
                       fields = "sst")$data %>% 
    mutate(time = as.Date(stringr::str_remove(time, "T00:00:00Z"))) %>% 
    dplyr::rename(t = time, temp = sst) %>% 
    dplyr::select(longitude, latitude, t, temp) %>% 
    na.omit()
}

# Date download range by start and end dates per year
dl_years <- data.frame(date_index = 1:5,
                       start = as.Date(c("1982-01-01", "1990-01-01", 
                                         "1998-01-01", "2006-01-01", "2014-01-01")),
                       end = as.Date(c("1989-12-31", "1997-12-31", 
                                       "2005-12-31", "2013-12-31", "2019-12-31")))


# Start and end of year dates for ALA data
min(cot_clean_date$eventDate, na.rm = TRUE)
max(cot_clean_date$eventDate, na.rm = TRUE)

# Get ranges by year
cot_data_ranges <- cot_clean_date |> 
  drop_na(year) |> 
  group_by(year) |> 
  summarise(n_obs = n(),
            start_y = min(eventDate, na.rm = TRUE),
            end_y = max(eventDate, na.rm = TRUE)) |> 
  print(n = Inf)

# Are some the same for start and end = once of obs
cot_data_ranges <- cot_data_ranges |> 
  mutate(once_off = start_y == end_y)

# SST data only goes back to 1981
cot_data_ranges |> 
  filter(year > 1981)

# Format data ranges as df
date_ranges <- cot_data_ranges |> 
  filter(year >= 1981) |> 
  dplyr::select(start_y, end_y) |> 
  mutate(date_index = row_number()) |> 
  dplyr::select(date_index, everything()) |> 
  rename(start = start_y, end = end_y) |> 
  mutate(start = as.character(start),
         end = as.character(end))

job::job({
system.time(
  OISST_data <- date_ranges %>% 
    group_by(date_index) %>% 
    group_modify(~OISST_sub_dl(.x)) %>% 
    ungroup() %>% 
    dplyr::select(longitude:temp)
)
  
  arrow::write_parquet(OISST_data, "data/SST.parquet")
})
```

```{r}
# Read in sea surface data
OISST_data <- read_parquet("data/SST.parquet")

# Create m and y variables
OISST_data_m_y <- OISST_data |> 
  mutate(month = month(t),
         year = year(t)) 

# Get yearly average temperature  for QLD
OISST_year <- OISST_data_m_y |> 
  group_by(year) |> 
  summarise(average_sst = mean(temp, na.rm = TRUE))  |> 
  ungroup() 

# Get average temperature for daily for QLD
daily_average <- OISST_data_m_y |> 
  group_by(t) |> 
  summarise(average_sst = mean(temp, na.rm = TRUE))  |> 
  ungroup() |> 
  mutate(t = as.POSIXct(t))

# Try plot
temp_plot <- 
  OISST_year |> 
  # filter(t < "1985-12-31") |> 
ggplot(aes(x = year, y = average_sst, group = 1)) +
  geom_line() + 
  # scale_x_datetime(date_breaks = "2 years", 
  #              labels = label_date_short()) + 
  scale_y_continuous(breaks = breaks_extended(10))


plot_layout(cot_obs / temp_plot)
```

# Get data for COT ALA data

```{r}
OISST_data <- open_dataset("data/SST.parquet")

cot_mainland |> 
  summarise(min_lat = min(decimalLatitude),
            max_lax = max(decimalLatitude),
            min_long = min(decimalLongitude),
            max_long = max(decimalLongitude))

QLD_SST <- OISST_data |> 
  filter(latitude >= -30, latitude <= -10.6,
         longitude >= 117, longitude <= 154) |> 
  collect()


cot_mainland$eventDate |> unique()
OISST_data$latitude |> summary()

ALA_COT_SST <- QLD_SST |> 
  filter(
    # latitude %in% round(cot_mainland$decimalLatitude |> unique(),3),
    # longitude %in% round(cot_mainland$decimalLongitude |> unique(),3),
    t %in% cot_mainland$eventDate
  ) 
```


```{r}
min(cot_mainland$decimalLatitude)
min(ALA_COT_SST$latitude)

max(cot_mainland$decimalLatitude)
max(ALA_COT_SST$latitude)

max(cot_mainland$decimalLongitude)
max(ALA_COT_SST$longitude)

daily_sst_vals <- ALA_COT_SST |> 
  group_by(t) |> 
  summarise(mean_sst = mean(temp),
            min_sst = min(temp),
            max_sst = max(temp),
            med_sst = median(temp))

cot_mainland_sst <- cot_mainland |> 
  left_join(daily_sst_vals, by = join_by(eventDate == t))
```

```{r}
cot_mainland_sst |> 
  ggplot(aes(x = eventDate, y = mean_sst)) + 
  geom_point() 

cot_sst_sf <- cot_mainland_sst |> 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), 
         crs = 4326) |> 
  mutate(year = year(eventDate), 
         month = month(eventDate)) |> 
  filter(year > 1981, ! is.na(year)) 

ggplot() + 
  geom_sf(data = aus_sf) + 
  geom_sf(data = cot_sst_sf, aes(color = mean_sst, size = 1)) + 
  coord_sf(ylim = c(-10, -25), xlim = c(141, 155)) + 
  theme_minimal() 
 

a<- ggplot() + 
  geom_sf(data = aus_sf) + 
  geom_sf(data = cot_sst_sf, aes(color = min_sst, size = 1)) + 
  coord_sf(ylim = c(-10, -25), xlim = c(141, 155)) + 
  theme_minimal() + 
  facet_wrap(~month) +
  ggtitle("min_sst")

ggplot() + 
  geom_sf(data = aus_sf) + 
  geom_sf(data = cot_sst_sf, aes(color = min_sst, size = 1)) + 
  coord_sf(ylim = c(-10, -25), xlim = c(141, 155)) + 
  theme_minimal() + 
  facet_wrap(~month) +
  ggtitle("min_sst")




b<- ggplot() + 
  geom_sf(data = aus_sf) + 
  geom_sf(data = cot_sst_sf, aes(color = max_sst, size = 1)) + 
  coord_sf(ylim = c(-10, -25), xlim = c(141, 155)) + 
  theme_minimal() + 
  facet_wrap(~month) +
  ggtitle("max_sst")

a+b
```


```{r}
cot_breeding <- cot_sst_sf |> 
  filter(month %in% c(11,12,1,2))

ggplot() + 
  geom_sf(data = aus_sf) + 
  geom_sf(data = cot_breeding, aes(color = max_sst, size = 1)) + 
  viridis::scale_color_viridis(option = "inferno") + 
  coord_sf(ylim = c(-10, -25), xlim = c(141, 155)) + 
  theme_minimal() + 
  facet_wrap(~month)
```

Get ALA and temp data around LIR

```{r}
lir = tibble(decimalLatitude = -14.667, 
             decimalLongitude = 145.467)

lir_sf <- lir |> 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), 
           crs = 4326) 

lir_5k <- lir_sf |> 
  sf::st_buffer(dist = 5000) 



ggplot() + 
  geom_sf(data = aus_sf) + 
  geom_sf(data = st_intersection(cot_breeding, lir_5k), aes(color = max_sst, size = 1)) + 
  viridis::scale_color_viridis(option = "inferno") + 
  coord_sf(ylim = c(-10, -25), xlim = c(141, 155)) + 
  theme_minimal() +
  facet_wrap(~month)

st_intersection(cot_breeding, lir_5k)$month
st_intersection(cot_breeding, lir_5k)$max_sst

st_intersection(cot_breeding, lir_5k)$min_sst
```

